### ISSUE TITLE
Missing dependency (properscoring) / (uncertainty_toolbox)

### ISSUE THREAD

**Issue by bbstats** [jjbrophy47/ibug#1]
Hi! This package looks great.

On first test of your sample code in the readme after pip installing ibug, I get this error:

`ModuleNotFoundError: No module named 'properscoring'`

**Comment by bbstats** [comment]
Looks like this is fixed here, just not in the pypi version

**Comment by jjbrophy47** [comment]
I've released a new version (0.0.7), which should contain the `uncertainty-toolbox`. Let me know if it still doesn't work for you.
