### ISSUE TITLE
error when running snippet code in README

### ISSUE THREAD

**Issue by yjhong89** [jjbrophy47/ibug#12]
Hi! 

When I running this code after ibug package, following error occurs.

```
from ibug import IBUGWrapper
from xgboost import XGBRegressor
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

# load diabetes dataset
data = load_diabetes()
X, y = data['data'], data['target']

# create train/val/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=1)

# train GBRT model
model = XGBRegressor().fit(X_train, y_train)

# extend GBRT model into a probabilistic estimator
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# predict mean and variance for unseen instances
location, scale = prob_model.pred_dist(X_test)

# return k highest-affinity neighbors for more flexible posterior modeling
location, scale, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)
```

### Errors
![image](https://github.com/user-attachments/assets/c809c5cb-216c-4aa5-b75d-8c195f62139d)

- After putting `reg_alpha=0` in xgb regressor, then following error occurs
![image](https://github.com/user-attachments/assets/65447668-4ce2-4976-8f54-2f968f21a84d)

- After 'scale_pos=1` in the same way, then following error occrus.
![image](https://github.com/user-attachments/assets/c9acdafd-256b-4f2c-84ef-520b5c3070b1)

###
- Would you give me any advice to handle these errors ??

Thanks.

**Comment by yjhong89** [comment]
Sorry. When I installed requirements.txt and it works. Another questions.
- Is `scale` means variance or deviation ?? 

```
# predict mean and variance for unseen instances
location, scale = prob_model.pred_dist(X_test)
```

- When I run above code, variance looks quite big.
![image](https://github.com/user-attachments/assets/12090b4d-cca7-4aeb-bbef-6ac730ee2131)

**Comment by jjbrophy47** [comment]
Hi @yjhong89, thanks for reaching out. What version of `ibug` are you using?

`scale` refers to standard deviation, I'll update the documentation to be clearer.

**Comment by yjhong89** [comment]
Thanks!
