### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by wangqf1997** [jjbrophy47/ibug#4]
Hello~

I found three AssertionError when I run the demo codes:
assert model_params['reg_alpha'] == 0
assert model_params['scale_pos_weight'] == 1
assert isinstance(self.bias, float)

I have to delete these lines so the demo codes can be run successfully. But I found that the output "location" is all the 'nan' values. Is there any problem?

**Comment by jjbrophy47** [comment]
Hmm, are you referring to the code in the "Quickstart" section in the readme? If so, what version of Python are you using, and what versions are you using for`xgboost` and `scikit-learn`?

**Comment by wangqf1997** [comment]
I have reinstalled the packages according to the requirements.txt. And I obtained the correct results. Thanks a lot.
