### ISSUE TITLE
from ._tree32 import _Tree32 is giving error when installing through pip

### ISSUE THREAD

**Issue by Pran97** [jjbrophy47/ibug#6]
ImportError: numpy.core.multiarray failed to import
when I used pip install ibug. Any reason why its not working for me?

**Comment by jjbrophy47** [comment]
Can you please provide:
- The version of python you're using.
- The version of ibug you installed.
- A complete code snippet that reproduces the error you are seeing.
Thank you!

**Comment by Pran97** [comment]
I am using Python 3.10.11

I have installed ibug-0.0.9

This specific error happens when I am trying - "from ibug import IBUGWrapper"

**Comment by jjbrophy47** [comment]
Hmm, what version of xgboost are you using? Or better yet, if you could provide a complete list of your dependencies and their versions (i.e., `pip3 list`).
