### ISSUE TITLE
How to do regression training with IBUGWrapper() containing multiple targets?

### ISSUE THREAD

**Issue by nguyenquocduongqnu** [jjbrophy47/ibug#8]
Your current job is great. 
Suppose there are multiple targets as follows:
```
X= data[['x1','x2','x3','x4','x5','x6']]
y= data[['target1', 'target2', 'target3', 'target4']]
```
I have a question: How to do regression training with IBUGWrapper() containing multiple targets?

**Comment by nguyenquocduongqnu** [comment]
@jjbrophy47 I look forward to a response from you. Thank you very much.

**Comment by jjbrophy47** [comment]
Hi @nguyenquocduongqnu, thank you for the question. Unfortunately, IBUG currently only supports a single target vector. Perhaps you could train a separate model for each target? Or you could open a pull request to change IBUG's code to support multiple targets.
