### ISSUE TITLE
Error when fitting the estimator

### ISSUE THREAD

**Issue by aclarkse** [jjbrophy47/ibug#9]
Hello,

I was using your implementation of BoostIn to fit my own data, but I came across an error, so I thought it might be due to some inherent inconsistency with my features. However, when fitting it to the iris data provided by the sklearn package (as cited in your example document in the repository), I came across this very same error:

180 # compute leaf derivative w.r.t. each train example in leaf_docs
181 numerator = g[leaf_docs, class_idx] + leaf_vals[leaf_idx] * h[leaf_docs, class_idx] # (no. docs,)
--> 182 denominator = np.sum(h[leaf_docs, class_idx]) + l2_leaf_reg
183 leaf_dvs[leaf_docs, boost_idx, class_idx] = numerator / denominator * lr # (no. docs,)
185 # update approximation

TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

Could you please give me some guidance as to what can be going wrong? For context, I am using an XGBoost model here, and I must provide scale_pos_weight=1 in order to avoid having an assertion error. It would be nice if this could be modified as well. Thank you

**Comment by jjbrophy47** [comment]
This has been fixed in v0.0.11, thank you!
